In [688]:
import numpy as np 
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from copy import deepcopy

from TensorDecisionTreeRegressor import *
#Debugging import
import importlib
var = 'TensorDecisionTreeRegressor'
package = importlib.import_module(var)
for name, value in package.__dict__.items():
    if not name.startswith("__"):
        globals()[name] = value

# Gradient Boosting Regressor Class
from GradientBoosting import *

# Compute the RMSE and RPE
def tensor_RMSE(truth,pred):
    return np.sqrt( np.linalg.norm(truth-pred,ord='fro')  )
def tensor_RPE(truth,pred):
    #res = []
    #for i in range(truth.shape[0]):
    err = tensor_RMSE(truth,pred)**2
    tru = tensor_RMSE(truth,truth*0.)**2
    return (err/tru)**2
    

In [689]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

# Load face dataset from FaceData.zip corresponding to Section 10 in Lock's 2018 paper https://arxiv.org/abs/1701.01037
# 1 11 15 23 24 31 (32) 33 51 63 | 68 71 90 99 102 117 121 129 135 146
my_seed = 68
np.random.seed(my_seed)
my_task = 'synTucker'
my_noise_scalar = 0.01
X_train = np.random.uniform(size=(100,12,6))
X_test = np.random.uniform(size=(100,12,6))
import numpy as np
import tensorly as tl
from tensorly.decomposition import tucker
from tensorly.tucker_tensor import tucker_to_tensor
def tucker_decompose_reconstruct(tensor, ranks):
    """
    Perform Tucker decomposition and then reconstruct the tensor.
    
    Args:
    tensor (np.ndarray): The input tensor.
    rank (tuple of ints): The rank for the Tucker decomposition for each mode.

    Returns:
    np.ndarray: Reconstructed tensor using the Tucker components.
    """
    # Decompose the tensor using Tucker decomposition
    tucker_result = tucker(tensor, rank=ranks)
    
    # Reconstruct the tensor from the Tucker components
    tensor_reconstructed = tucker_to_tensor(tucker_result)
    
    return tensor_reconstructed

# Set the desired ranks for the decomposition
desired_ranks = (4, 4, 4)  # These ranks need to be tuned according to the specific tensor dimensions
# Perform decomposition and reconstruction
X_train_reconstructed = tucker_decompose_reconstruct(X_train, desired_ranks)
X_test_reconstructed = tucker_decompose_reconstruct(X_test, desired_ranks)

print(X_train_reconstructed.shape,X_test_reconstructed.shape)
# Optionally, print or compare the original and reconstructed tensors
print("Original X_train[0]:", X_train[0])
print("Reconstructed X_train[0]:", X_train_reconstructed[0])
print("\nOriginal X_test[0]:", X_test[0])
print("Reconstructed X_test[0]:", X_test_reconstructed[0])
#
y_train = np.zeros(shape=(100,7))
y_test = np.zeros(shape=(100,7))
assert (y_train.shape[1]==y_test.shape[1])
for i in range(y_test.shape[1]):
    N_size = y_test.shape[0]
    y_train[:,i] = (X_train_reconstructed[:,0,1])**2 - X_train_reconstructed[:,0,0] + my_noise_scalar*np.random.uniform(size=(N_size,))
    y_test[:,i] = (X_test_reconstructed[:,0,1])**2 - X_test_reconstructed[:,0,0] + my_noise_scalar*np.random.uniform(size=(N_size,))
        
Lock_X_train = X_train
Lock_X_test = X_test
Lock_y_train = y_train
Lock_y_test = y_test
Lock_X_train = Lock_X_train[:,:,:]
Lock_X_test = Lock_X_test[:,:,:]
Lock_y_train = Lock_y_train[:,:]
Lock_y_test = Lock_y_test[:,:]

np.save(my_task+"_X_train.npy",Lock_X_train)
np.save(my_task+"_X_test.npy",Lock_X_test)
np.save(my_task+"_y_train.npy",Lock_y_test)
np.save(my_task+"_y_test.npy",Lock_y_test)

print(Lock_X_train.shape,Lock_X_test.shape)
print(Lock_y_train.shape,Lock_y_test.shape)
my_rank = 2
my_n_mode = len(Lock_X_train.shape)


(100, 12, 6) (100, 12, 6)
Original X_train[0]: [[0.25937147 0.04336105 0.58203034 0.11251217 0.61077678 0.29638796]
 [0.80725219 0.09483773 0.70010037 0.93289602 0.8422089  0.79995898]
 [0.97282329 0.53608642 0.50723281 0.95483086 0.77569678 0.59055587]
 [0.16887804 0.18339044 0.0317532  0.22962335 0.52991138 0.69191556]
 [0.28996716 0.09009975 0.98563455 0.77317084 0.54878549 0.15826334]
 [0.75044303 0.52469456 0.80580271 0.71656553 0.0158944  0.51318498]
 [0.6730693  0.68454134 0.48631006 0.99791941 0.35928526 0.3664124 ]
 [0.13592195 0.33018249 0.17031529 0.84042189 0.60552385 0.4553598 ]
 [0.70239643 0.99172067 0.63672086 0.01832205 0.13956102 0.64533608]
 [0.00468777 0.07225554 0.56829157 0.66938709 0.84744455 0.25496099]
 [0.73639142 0.99719593 0.02433295 0.99469129 0.10009659 0.79671713]
 [0.07480246 0.2821466  0.0856984  0.90929196 0.72246251 0.78461154]]
Reconstructed X_train[0]: [[0.50522575 0.55349781 0.50718159 0.55467325 0.50896292 0.52817944]
 [0.52896868 0.58116084 0.516

In [690]:
# Initialize Gradient Boosting Regressor with a simple decision tree as weak learner
weak_learner = TensorDecisionTreeRegressor(max_depth=3, min_samples_split=4, split_method='variance',split_rank=my_rank,n_mode=my_n_mode)
weak_learner.use_mean_as_threshold = True
weak_learner.sample_rate = 1.0
gradient_boosting_regressor = GradientBoostingRegressor(
    n_estimators=10,
    learning_rate=0.1,
    weak_learner=weak_learner
)
gradient_boosting_regressor.pruning = True
# Fit a single tree model
weak_learner.fit(Lock_X_train, Lock_y_train[:,0])
weak_predictions = weak_learner.predict(Lock_X_test)


# Fit the Gradient Boosting model
gradient_boosting_regressor.fit(Lock_X_train, Lock_y_train[:,0], Lock_X_test, Lock_y_test[:,0])

# Predict
entrywise_CP = gradient_boosting_regressor.predict(Lock_X_test,regression_method='cp')
entrywise_Tucker = gradient_boosting_regressor.predict(Lock_X_test,regression_method='tucker')
#np.save('entrywise_CP_predictions_rank_'+str(my_rank)+'_'+my_task+'.npy',entrywise_CP)
#np.save('entrywise_Tucker_predictions_rank_'+str(my_rank)+'_'+my_task+'.npy',entrywise_Tucker)


# In[21]:


# Display the RMSE
print(entrywise_CP.shape)
print(entrywise_Tucker.shape)
print(np.sqrt(np.mean((Lock_y_test[:,0]-entrywise_CP)**2)))
print(np.sqrt(np.mean((Lock_y_test[:,0]-entrywise_Tucker)**2)))


search size: 72
(8, 5) 0.5100637623739397 0.006118053633842409
search size: 72
(10, 3) 0.569614805670553 0.0040122821240602775
search size: 72
(7, 5) 0.42110334143798117 0.0037187498391674577
search size: 72
(6, 1) 0.4435206052568502 0.0014189100240853635
search size: 72
(9, 0) 0.4011258610589309 0.005530959422011867
search size: 72
(11, 0) 0.4977559383453827 0.003620365960810335
search size: 72
(4, 5) 0.5245679487821951 0.0037996075890039103


/home/akirahoriguchi/anaconda3/lib/python3.8/site-packages/tensorly/regression/tucker_regression.py:126: RuntimeWarning: divide by zero encountered in double_scalars
  weight_evolution = abs(norm_W[-1] - norm_W[-2]) / norm_W[-1]
/home/akirahoriguchi/anaconda3/lib/python3.8/site-packages/tensorly/regression/tucker_regression.py:126: RuntimeWarning: invalid value encountered in double_scalars
  weight_evolution = abs(norm_W[-1] - norm_W[-2]) / norm_W[-1]


0 0 training MSE === 0.056451243609007815
0 0 testing MSE === 0.07634273785016635
search size: 72
(8, 5) 0.5100637623739397 0.006118053633842409
search size: 72
(10, 3) 0.569614805670553 0.0040122821240602775
search size: 72
(7, 5) 0.42110334143798117 0.0037187498391674577
search size: 72
(6, 1) 0.4435206052568502 0.0014189100240853635
search size: 72
(9, 0) 0.4011258610589309 0.005530959422011867
search size: 72
(11, 0) 0.4977559383453827 0.003620365960810335
search size: 72
(4, 5) 0.5245679487821951 0.0037996075890039103
pruning a depth= 0
pruning a depth= 1
pruning a depth= 2
pruning a depth= 2
pruning a depth= 1
pruning a depth= 2
pruning a depth= 2
0 1 training MSE === 0.04639361283647062
0 1 testing MSE === 0.06474116560587391
search size: 72
(8, 5) 0.5100637623739397 0.00611805363384241
search size: 72
(10, 3) 0.569614805670553 0.004012282124060277
search size: 72
(7, 5) 0.42110334143798117 0.003718749839167457
search size: 72
(6, 1) 0.4435206052568502 0.0014189100240853633
sear

/home/akirahoriguchi/anaconda3/lib/python3.8/site-packages/tensorly/regression/cp_regression.py:116: RuntimeWarning: divide by zero encountered in double_scalars
  weight_evolution = abs(norm_W[-1] - norm_W[-2]) / norm_W[-1]
/home/akirahoriguchi/anaconda3/lib/python3.8/site-packages/tensorly/regression/cp_regression.py:116: RuntimeWarning: invalid value encountered in double_scalars
  weight_evolution = abs(norm_W[-1] - norm_W[-2]) / norm_W[-1]


pruning a depth= 0
pruning a depth= 1
pruning a depth= 2
pruning a depth= 2
pruning a depth= 1
pruning a depth= 2
pruning a depth= 2
0 9 training MSE === 0.01146158913647443
0 9 testing MSE === 0.021895214259828336
search size: 72
(8, 5) 0.5100637623739397 0.006118053633842409
search size: 72
(10, 3) 0.569614805670553 0.004012282124060277
search size: 72
(7, 5) 0.42110334143798117 0.0037187498391674564
search size: 72
(6, 1) 0.4435206052568502 0.0014189100240853633
search size: 72
(9, 0) 0.4011258610589309 0.005530959422011867
search size: 72
(11, 0) 0.4977559383453827 0.003620365960810335
search size: 72
(4, 5) 0.5245679487821951 0.00379960758900391
pruning a depth= 0
pruning a depth= 1
pruning a depth= 2
pruning a depth= 2
pruning a depth= 1
pruning a depth= 2
pruning a depth= 2
(100,)
(100,)
0.13915476745819536
0.14572709705320283


In [691]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from concurrent.futures import ThreadPoolExecutor
import copy
class GenericTensorRegressor:
    def __init__(self, regressor):
        self.regressor = regressor
        #self.regressor_params = regressor_params
        self.models = []
        
    def fit(self, X_train, y_train):
        # Flatten the tensor if it has more than 2 dimensions
        if y_train.ndim > 2:
            y_train = y_train.reshape(y_train.shape[0], -1)
        
        # Fit a separate model for each column (or flattened column) of y_train
        self.models = []
        for i in range(y_train.shape[1]):
            print(i,',',y_train.shape[1])
            model = copy.deepcopy(self.regressor)
            #if self.regressor is TensorDecisionTreeRegressor:
            #    model.use_mean_as_threshold = True
            model.fit(X_train, y_train[:, i])
            self.models.append(model)

    def fit_parallel(self, X_train, y_train):
        # Flatten the tensor if it has more than 2 dimensions
        if y_train.ndim > 2:
            y_train = y_train.reshape(y_train.shape[0], -1)
        
        # Helper function to fit a model for a specific target column
        def fit_model(column_index):
            print('Fitting model ',column_index)
            model = self.regressor(**self.regressor_params)
            # Example conditional feature, uncomment if needed:
            # if self.regressor is TensorDecisionTreeRegressor:
            #     model.use_mean_as_threshold = True
            model.fit(X_train, y_train[:, column_index])
            return model
        
        # Use ThreadPoolExecutor to parallelize the fitting process
        with ThreadPoolExecutor() as executor:
            self.models = list(executor.map(fit_model, range(y_train.shape[1])))


    def predict(self, X_test, regression_method, output_shape=None):
        # Predict with each model and concatenate the results
        predictions = [model.predict(X_test,regression_method=regression_method) for model in self.models]
        predictions = np.column_stack(predictions)

        # Reshape the predictions to the original tensor shape if specified
        if output_shape is not None and len(output_shape) > 2:
            predictions = predictions.reshape((-1, *output_shape[1:]))
        
        return predictions

# The GenericTensorRegressor can now handle various shapes of y_train automatically.
# It will be used within the TensorOnTensorRegressor class if the output tensor requires it.



In [692]:
# For DecisionTreeRegressor
#tensor_regressor = GenericTensorRegressor(DecisionTreeRegressor)
#tensor_regressor.fit(X_train, y_train)
#predictions = tensor_regressor.predict(X_test)

# For GradientBoostingRegressor
#tensor_regressor = GenericTensorRegressor(GradientBoostingRegressor, n_estimators=50, learning_rate=0.01, loss_function='mse')
#tensor_regressor.fit(X_train, y_train)
#predictions = tensor_regressor.predict(X_test)

# For TensorDecisionTreeRegressor
#weak_learner = TensorDecisionTreeRegressor(max_depth=1, min_samples_split=2, split_method='variance',split_rank=2,n_mode=4)
#weak_learner.use_mean_as_threshold = True
#weak_learner.sample_rate = 0.0001
tensor_regressor = GenericTensorRegressor(gradient_boosting_regressor)
tensor_regressor.fit(Lock_X_train, Lock_y_train)
TTentrywise_GB_CP = tensor_regressor.predict( Lock_X_test,regression_method='cp')
TTentrywise_GB_Tucker = tensor_regressor.predict( Lock_X_test,regression_method='tucker')
np.save('TTentrywise_GB_CP_predictions_rank_'+str(my_rank)+'_'+my_task+'.npy',TTentrywise_GB_CP)
np.save('TTentrywise_GB_Tucker_predictions_rank_'+str(my_rank)+'_'+my_task+'.npy',TTentrywise_GB_Tucker)

0 , 7
0 0 training MSE === 0.009951992713718587
search size: 72
(8, 5) 0.5100637623739397 0.00611805363384241
search size: 72
(10, 3) 0.569614805670553 0.0040122821240602775
search size: 72
(7, 5) 0.42110334143798117 0.0037187498391674572
search size: 72
(6, 1) 0.4435206052568502 0.0014189100240853633
search size: 72
(9, 0) 0.4011258610589309 0.005530959422011867
search size: 72
(11, 0) 0.4977559383453827 0.0036203659608103345
search size: 72
(4, 5) 0.5245679487821951 0.00379960758900391
pruning a depth= 0
pruning a depth= 1
pruning a depth= 2
pruning a depth= 2
pruning a depth= 1
pruning a depth= 2
pruning a depth= 2
0 1 training MSE === 0.012580875028770436
search size: 72
(8, 5) 0.5100637623739397 0.006118053633842409
search size: 72
(10, 3) 0.569614805670553 0.004012282124060277
search size: 72
(7, 5) 0.42110334143798117 0.003718749839167457
search size: 72
(6, 1) 0.4435206052568502 0.0014189100240853635
search size: 72
(9, 0) 0.4011258610589309 0.005530959422011867
search size: 72

In [693]:
print(TTentrywise_GB_CP.shape)
print(TTentrywise_GB_Tucker.shape)
print(tensor_RMSE(Lock_y_test,TTentrywise_GB_CP))
print(tensor_RMSE(Lock_y_test,TTentrywise_GB_Tucker))
    
print(tensor_RPE(Lock_y_test,TTentrywise_GB_CP))
print(tensor_RPE(Lock_y_test,TTentrywise_GB_Tucker))

(100, 7)
(100, 7)
2.1286991771990227
2.175118577686314
0.3838407980864113
0.41843279495969044


In [694]:
class TensorOnTensorRegressor:
    def __init__(self,regressor,rank, decomposition_type='cp'):
        self.decomposition_type = decomposition_type
        self.rank = rank
        self.regressor = regressor
        #self.regressor_params = regressor_params
        self.models = []
        self.decomposition_factors = None
        self.core_tensor = None

    def fit(self, X_train, y_train):
        if self.decomposition_type == 'cp':
            weights, factors = parafac(y_train, rank=self.rank)
            self.decomposition_weights = weights
            self.decomposition_factors = factors
            first_factor = factors[0]

            if first_factor.ndim > 1 and first_factor.shape[1] > 1:
                model = GenericTensorRegressor(regressor=self.regressor)
            else:
                raise RuntimeError('CP Error: Must satisfy first_factor.ndim > 1 and first_factor.shape[1] > 1')
            model.fit(X_train, first_factor)
            self.models.append(model)

        elif self.decomposition_type == 'tucker':
            core, factors = tucker(y_train, rank=[self.rank]*len(y_train.shape))
            self.core_tensor = core
            self.decomposition_factors = factors
            first_factor = factors[0]

            if first_factor.ndim > 1 and first_factor.shape[1] > 1:
                tensor_model = GenericTensorRegressor(regressor=self.regressor)
            else:
                raise RuntimeError('Tucker Error: Must satisfy first_factor.ndim > 1 and first_factor.shape[1] > 1')
            tensor_model.fit(X_train, first_factor)
            self.models.append(tensor_model)

        else:
            raise ValueError("Unsupported decomposition type. Choose 'cp' or 'tucker'.")

    def predict(self, X_test, regression_method):
        predicted_components = [model.predict(X_test,regression_method=regression_method) for model in self.models]
        print(len(predicted_components),'?',predicted_components[0].shape)
        if self.decomposition_type == 'cp':
            # Reconstruct using cp_to_tensor for CP decomposition
            fac_list = [predicted_components[0]]
            for i in range(len(self.decomposition_factors)):
                print(i,'/',len(self.decomposition_factors))
                if i == 0:
                    continue#Skip the training X factor
                fac_list.append(self.decomposition_factors[i])
                print(self.decomposition_factors[i].shape)
            reconstructed = tl.cp_to_tensor((self.decomposition_weights,fac_list))
            return reconstructed
        elif self.decomposition_type == 'tucker':
            # Reconstruct using tucker_to_tensor for Tucker decomposition
            reconstructed = tl.tucker_to_tensor((self.core_tensor, [predicted_components[0]] + self.decomposition_factors[1:]))
            return reconstructed

In [695]:
# Example usage:
tensorOnTensor_reg_CP = TensorOnTensorRegressor(gradient_boosting_regressor,rank=my_rank,decomposition_type='cp')
tensorOnTensor_reg_CP.fit(Lock_X_train, Lock_y_train)
TTlowrank_CP = tensorOnTensor_reg_CP.predict(Lock_X_test,regression_method='cp')
tensorOnTensor_reg_Tucker = TensorOnTensorRegressor(gradient_boosting_regressor,rank=my_rank,decomposition_type='tucker')
tensorOnTensor_reg_Tucker.fit(Lock_X_train, Lock_y_train)
TTlowrank_Tucker = tensorOnTensor_reg_Tucker.predict(Lock_X_test,regression_method='tucker')

0 , 2
0 0 training MSE === 0.234033978883913
search size: 72
(8, 5) 0.5100637623739397 0.04307347797805999
search size: 72
(10, 3) 0.569614805670553 0.028466619856148095
search size: 72
(7, 5) 0.42110334143798117 0.02740604486325788
search size: 72
(6, 1) 0.4435206052568502 0.009894196775808311
search size: 72
(9, 0) 0.4011258610589309 0.03885990274202453
search size: 72
(11, 0) 0.4977559383453827 0.02521857078237489
search size: 72
(4, 5) 0.5245679487821951 0.026855212724211874
pruning a depth= 0
pruning a depth= 1
pruning a depth= 2
pruning a depth= 2
pruning a depth= 1
pruning a depth= 2
pruning a depth= 2
0 1 training MSE === 0.2137574937488259
search size: 72
(8, 5) 0.5100637623739397 0.04307347797806001
search size: 72
(10, 3) 0.569614805670553 0.028466619856148102
search size: 72
(7, 5) 0.42110334143798117 0.02740604486325788
search size: 72
(6, 1) 0.4435206052568502 0.009894196775808313
search size: 72
(9, 0) 0.4011258610589309 0.038859902742024534
search size: 72
(11, 0) 0.497

In [696]:
print(TTlowrank_CP.shape)
print(TTlowrank_Tucker.shape)
print(tensor_RMSE(Lock_y_test,TTlowrank_CP))
print(tensor_RMSE(Lock_y_test,TTlowrank_Tucker))
np.save('TTlowrank_CP_predictions_rank_'+str(my_rank)+'_'+my_task+'.npy',TTlowrank_CP)
np.save('TTlowrank_Tucker_predictions_rank_'+str(my_rank)+'_'+my_task+'.npy',TTlowrank_Tucker)

(100, 7)
(100, 7)
2.0083703258523875
1.6275034835872764


In [697]:
Lock_y_test.shape

(100, 7)

In [698]:
import subprocess
#import sys
def run_r_script(rank,task):
    # Define the path to the R script
    r_script_path = './tensorOutput_rrr_synthetic.R'
    
    # Define the command to run the R script with Rscript and pass the rank as an argument
    command = ['Rscript', r_script_path, str(rank),str(task)]
    
    # Run the command
    result = subprocess.run(command, capture_output=True, text=True)
    
    # Print the output of the R script
    print('STDOUT:', result.stdout)
    print('STDERR:', result.stderr)

# Example usage: run the R script with rank 2
run_r_script(my_rank,my_task)

STDOUT: [1] 100  12   6
[1] 100  12   6
[1] 100   7
[1] 100   7
[1] 2
[1] 100   7
[1] 100   7
[1] 0.1213654
[1] 0.1159711
[1] "tensorOutput_rrr_synthetic.R done."

STDERR: 


In [699]:
rrr = np.load("rrr_predictions_rank_"+str(my_rank)+'_'+my_task+'.npy')
print(tensor_RMSE(Lock_y_test,rrr))
print(tensor_RPE(Lock_y_test,rrr))
rrrBayes = np.load("rrrBayes_predictions_rank_"+str(my_rank)+'_'+my_task+'.npy')
print(tensor_RMSE(Lock_y_test,rrrBayes))
print(tensor_RPE(Lock_y_test,rrrBayes))

1.7919398032545821
0.19274700105788803
1.7516653043393988
0.17599424877748843


In [700]:
import datetime
def create_and_write_file():
    # Get current datetime
    now = datetime.datetime.now()
    
    # Format datetime as 'DDMMYY_HHMM'
    formatted_date = now.strftime('%d%m%y_%H%M%S')
    
    # Create filename
    filename = f'synthetic_result_{formatted_date}.txt'
    dataname = f'synthetic_datset_{formatted_date}'
    # Lines to write
    lines_to_write = [
        "my_task",
        my_task,
        "my_rank",
        my_rank,
        "my_noise_scalar",
        my_noise_scalar,
        "my_seed",
        my_seed,
        "X_train.shape",
        X_train.shape,
        "X_test.shape",
        X_test.shape,
        "y_train.shape",
        y_train.shape,
        "y_test.shape",
        y_test.shape,
        "---*ALL METRICS BELOW* are evaluated on testing set---",
        "TTentrywise_CP_RMSE",   
        tensor_RMSE(Lock_y_test,TTentrywise_GB_CP),
        "TTentrywise_CP_RPE",   
        tensor_RPE(Lock_y_test,TTentrywise_GB_CP),
        "TTentrywise_Tucker_RMSE",
        tensor_RMSE(Lock_y_test,TTentrywise_GB_Tucker),
        "TTentrywise_Tucker_RPE",   
        tensor_RPE(Lock_y_test,TTentrywise_GB_Tucker),
        "TTlowrank_CP_RMSE",   
        tensor_RMSE(Lock_y_test,TTlowrank_CP),
        "TTlowrank_CP_RPE",   
        tensor_RPE(Lock_y_test,TTlowrank_CP),
        "TTlowrank_Tucker_RMSE",
        tensor_RMSE(Lock_y_test,TTlowrank_Tucker),
        "TTlowrank_Tucker_RPE",   
        tensor_RPE(Lock_y_test,TTlowrank_Tucker),
        "rrr_RMSE",
        tensor_RMSE(Lock_y_test,rrr),
        "rrr_RPE",
        tensor_RPE(Lock_y_test,rrr),
        "rrrBayes_RMSE",
        tensor_RMSE(Lock_y_test,rrrBayes),
        "rrrBayes_RPE",
        tensor_RPE(Lock_y_test,rrrBayes)
    ]
    #print(lines_to_write,sep='\n')
    # Write lines to the file
    with open(filename, 'w') as file:
        for line in lines_to_write:
            file.write(str(line) + '\n')
            print(line)
    
    print(f"File '{filename}' has been created and written successfully.")
    np.save(my_task+"_X_train.npy",X_train)
    np.save(my_task+"_X_test.npy",X_test)
    np.save(my_task+"_y_train.npy",y_train)
    np.save(my_task+"_y_test.npy",y_test)
# Call the function to execute
create_and_write_file()


my_task
synTucker
my_rank
2
my_noise_scalar
0.01
my_seed
68
X_train.shape
(100, 12, 6)
X_test.shape
(100, 12, 6)
y_train.shape
(100, 7)
y_test.shape
(100, 7)
---*ALL METRICS BELOW* are evaluated on testing set---
TTentrywise_CP_RMSE
2.1286991771990227
TTentrywise_CP_RPE
0.3838407980864113
TTentrywise_Tucker_RMSE
2.175118577686314
TTentrywise_Tucker_RPE
0.41843279495969044
TTlowrank_CP_RMSE
2.0083703258523875
TTlowrank_CP_RPE
0.3041369232986805
TTlowrank_Tucker_RMSE
1.6275034835872764
TTlowrank_Tucker_RPE
0.13115403965035372
rrr_RMSE
1.7919398032545821
rrr_RPE
0.19274700105788803
rrrBayes_RMSE
1.7516653043393988
rrrBayes_RPE
0.17599424877748843
File 'synthetic_result_130524_204543.txt' has been created and written successfully.


In [701]:
import os
duration = .5  # seconds
freq = 220  # Hz
os.system('play -nq -t alsa synth {} sine {}'.format(duration, freq))

32512